# Generated by Django 3.2.16 on 2024-05-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armenia',
            fields=[
                ('Trade_name_rus', models.CharField(max_length=256)),
                ('Registrator_tran', models.CharField(max_length=256)),
                ('Registrator_country', models.CharField(max_length=256)),
                ('Producer_tran', models.CharField(max_length=256)),
                ('Producer_country', models.CharField(max_length=256)),
                ('Dosage_form_full_name', models.CharField(max_length=256)),
                ('Dose', models.CharField(max_length=256)),
                ('Sc_name', models.CharField(max_length=256)),
                ('Recipe_status', models.CharField(max_length=256)),
                ('As_name_rus', models.CharField(max_length=256)),
                ('num', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GRLS',
            fields=[
                ('Trade_name_rus', models.CharField(max_length=256)),
                ('Registrator_tran', models.CharField(max_length=256)),
                ('Registrator_country', models.CharField(max_length=256)),
                ('Producer_tran', models.CharField(max_length=256)),
                ('Producer_country', models.CharField(max_length=256)),
                ('Dosage_form_full_name', models.CharField(max_length=256)),
                ('Dose', models.CharField(max_length=256)),
                ('Sc_name', models.CharField(max_length=256)),
                ('Recipe_status', models.CharField(max_length=256)),
                ('As_name_rus', models.CharField(max_length=256)),
                ('num', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Kazakhstan',
            fields=[
                ('Trade_name_rus', models.CharField(max_length=256)),
                ('Registrator_tran', models.CharField(max_length=256)),
                ('Registrator_country', models.CharField(max_length=256)),
                ('Producer_tran', models.CharField(max_length=256)),
                ('Producer_country', models.CharField(max_length=256)),
                ('Dosage_form_full_name', models.CharField(max_length=256)),
                ('Dose', models.CharField(max_length=256)),
                ('Sc_name', models.CharField(max_length=256)),
                ('Recipe_status', models.CharField(max_length=256)),
                ('As_name_rus', models.CharField(max_length=256)),
                ('num', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Kyrgyzstan',
            fields=[
                ('Trade_name_rus', models.CharField(max_length=256)),
                ('Registrator_tran', models.CharField(max_length=256)),
                ('Registrator_country', models.CharField(max_length=256)),
                ('Producer_tran', models.CharField(max_length=256)),
                ('Producer_country', models.CharField(max_length=256)),
                ('Dosage_form_full_name', models.CharField(max_length=256)),
                ('Dose', models.CharField(max_length=256)),
                ('Sc_name', models.CharField(max_length=256)),
                ('Recipe_status', models.CharField(max_length=256)),
                ('As_name_rus', models.CharField(max_length=256)),
                ('num', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
