# Generated by Django 3.2.16 on 2024-05-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armenia',
            name='Producer_tran',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='armenia',
            name='Registrator_country',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='grls',
            name='Producer_tran',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='grls',
            name='Registrator_country',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='kazakhstan',
            name='Producer_tran',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='kazakhstan',
            name='Registrator_country',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='kyrgyzstan',
            name='Producer_tran',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='kyrgyzstan',
            name='Registrator_country',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
