# Generated by Django 3.2.16 on 2024-05-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20240514_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armenia',
            name='Registrator_country',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='armenia',
            name='Sc_name',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='grls',
            name='Registrator_country',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='grls',
            name='Sc_name',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='kazakhstan',
            name='Registrator_country',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='kazakhstan',
            name='Sc_name',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='kyrgyzstan',
            name='Registrator_country',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='kyrgyzstan',
            name='Sc_name',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
