# Generated by Django 3.2.16 on 2024-05-14 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20240514_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armenia',
            name='Dosage_form_full_name',
        ),
        migrations.RemoveField(
            model_name='armenia',
            name='Dose',
        ),
        migrations.RemoveField(
            model_name='armenia',
            name='Producer_country',
        ),
        migrations.RemoveField(
            model_name='armenia',
            name='Recipe_status',
        ),
        migrations.RemoveField(
            model_name='armenia',
            name='Registrator_tran',
        ),
        migrations.RemoveField(
            model_name='grls',
            name='Dosage_form_full_name',
        ),
        migrations.RemoveField(
            model_name='grls',
            name='Dose',
        ),
        migrations.RemoveField(
            model_name='grls',
            name='Producer_country',
        ),
        migrations.RemoveField(
            model_name='grls',
            name='Recipe_status',
        ),
        migrations.RemoveField(
            model_name='grls',
            name='Registrator_tran',
        ),
        migrations.RemoveField(
            model_name='kazakhstan',
            name='Dosage_form_full_name',
        ),
        migrations.RemoveField(
            model_name='kazakhstan',
            name='Dose',
        ),
        migrations.RemoveField(
            model_name='kazakhstan',
            name='Producer_country',
        ),
        migrations.RemoveField(
            model_name='kazakhstan',
            name='Producer_tran',
        ),
        migrations.RemoveField(
            model_name='kazakhstan',
            name='Recipe_status',
        ),
        migrations.RemoveField(
            model_name='kyrgyzstan',
            name='Dosage_form_full_name',
        ),
        migrations.RemoveField(
            model_name='kyrgyzstan',
            name='Dose',
        ),
        migrations.RemoveField(
            model_name='kyrgyzstan',
            name='Producer_country',
        ),
        migrations.RemoveField(
            model_name='kyrgyzstan',
            name='Producer_tran',
        ),
        migrations.RemoveField(
            model_name='kyrgyzstan',
            name='Recipe_status',
        ),
    ]
